-- Star schema for the simulated retail data warehouse.
-- Statements are separated by a line containing only "/".

CREATE TABLE DIM_DATE (
    DATE_KEY        NUMBER(8)     PRIMARY KEY,
    FULL_DATE       DATE          NOT NULL,
    YEAR_NUM        NUMBER(4)     NOT NULL,
    QUARTER_NUM     NUMBER(1)     NOT NULL,
    MONTH_NUM       NUMBER(2)     NOT NULL,
    YEAR_MONTH      VARCHAR2(7 CHAR)   NOT NULL,
    ISO_WEEK        NUMBER(2)     NOT NULL,
    DAY_OF_WEEK     NUMBER(1)     NOT NULL,
    WEEKDAY_NAME    VARCHAR2(12 CHAR)  NOT NULL,
    IS_WEEKEND      CHAR(1)       NOT NULL,
    HOLIDAY_NAME    VARCHAR2(40 CHAR)
)
/
CREATE TABLE DIM_STORE (
    STORE_ID        NUMBER(6)     PRIMARY KEY,
    STORE_CODE      VARCHAR2(10 CHAR)  NOT NULL UNIQUE,
    STORE_NAME      VARCHAR2(60 CHAR)  NOT NULL,
    CITY            VARCHAR2(30 CHAR)  NOT NULL,
    REGION_CODE     VARCHAR2(2 CHAR)   NOT NULL,
    REGION_NAME     VARCHAR2(12 CHAR)  NOT NULL,
    STORE_TYPE      VARCHAR2(20 CHAR)  NOT NULL,
    FLOOR_AREA_PING NUMBER(6)     NOT NULL,
    OPEN_DATE       DATE          NOT NULL
)
/
CREATE TABLE DIM_CHANNEL (
    CHANNEL_ID      NUMBER(3)     PRIMARY KEY,
    CHANNEL_CODE    VARCHAR2(20 CHAR)  NOT NULL UNIQUE,
    CHANNEL_NAME    VARCHAR2(30 CHAR)  NOT NULL,
    CHANNEL_TYPE    VARCHAR2(12 CHAR)  NOT NULL
)
/
CREATE TABLE DIM_PRODUCT (
    PRODUCT_ID      NUMBER(6)     PRIMARY KEY,
    PRODUCT_CODE    VARCHAR2(10 CHAR)  NOT NULL UNIQUE,
    PRODUCT_NAME    VARCHAR2(80 CHAR)  NOT NULL,
    CATEGORY        VARCHAR2(30 CHAR)  NOT NULL,
    BRAND           VARCHAR2(40 CHAR)  NOT NULL,
    LIST_PRICE      NUMBER(10,2)  NOT NULL,
    STD_COST        NUMBER(10,2)  NOT NULL
)
/
CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_ID      NUMBER(8)    PRIMARY KEY,
    CUSTOMER_CODE    VARCHAR2(12 CHAR) NOT NULL UNIQUE,
    SEGMENT          VARCHAR2(20 CHAR) NOT NULL,
    GENDER           VARCHAR2(6 CHAR)  NOT NULL,
    AGE_GROUP        VARCHAR2(10 CHAR) NOT NULL,
    HOME_REGION_NAME VARCHAR2(12 CHAR) NOT NULL,
    JOIN_DATE        DATE         NOT NULL
)
/
CREATE TABLE FACT_SALES (
    ORDER_ID        NUMBER(15)    NOT NULL,
    LINE_NO         NUMBER(3)     NOT NULL,
    DATE_KEY        NUMBER(8)     NOT NULL REFERENCES DIM_DATE (DATE_KEY),
    STORE_ID        NUMBER(6)     NOT NULL REFERENCES DIM_STORE (STORE_ID),
    CHANNEL_ID      NUMBER(3)     NOT NULL REFERENCES DIM_CHANNEL (CHANNEL_ID),
    PRODUCT_ID      NUMBER(6)     NOT NULL REFERENCES DIM_PRODUCT (PRODUCT_ID),
    CUSTOMER_ID     NUMBER(8)     NOT NULL REFERENCES DIM_CUSTOMER (CUSTOMER_ID),
    QUANTITY        NUMBER(6)     NOT NULL,
    UNIT_PRICE      NUMBER(10,2)  NOT NULL,
    DISCOUNT_AMOUNT NUMBER(12,2)  NOT NULL,
    SALES_AMOUNT    NUMBER(12,2)  NOT NULL,
    COST_AMOUNT     NUMBER(12,2)  NOT NULL,
    CONSTRAINT PK_FACT_SALES PRIMARY KEY (ORDER_ID, LINE_NO)
)
/
CREATE INDEX IX_FACT_SALES_DATE ON FACT_SALES (DATE_KEY)
/
CREATE TABLE ETL_BATCH_LOG (
    BUSINESS_DATE_KEY NUMBER(8)    PRIMARY KEY REFERENCES DIM_DATE (DATE_KEY),
    RUN_AT            TIMESTAMP    NOT NULL,
    ROWS_LOADED       NUMBER(10)   NOT NULL,
    STATUS            VARCHAR2(12 CHAR) NOT NULL,
    MESSAGE           VARCHAR2(400 CHAR)
)
/
COMMENT ON TABLE FACT_SALES IS '銷售明細（訂單明細層級）。SALES_AMOUNT 為折扣後淨額 = QUANTITY * UNIT_PRICE - DISCOUNT_AMOUNT'
/
COMMENT ON TABLE DIM_STORE IS '門市。線上訂單依顧客所在區域歸屬到門市'
/
COMMENT ON TABLE DIM_CHANNEL IS '銷售通路：門市、官網、電商平台'
/
COMMENT ON TABLE DIM_CUSTOMER IS '顧客。每個區域有一筆「非會員」虛擬顧客，代表未登入會員的門市消費'
/
COMMENT ON TABLE ETL_BATCH_LOG IS 'ETL 每日批次紀錄：每個營業日載入筆數與狀態'
/
COMMENT ON COLUMN FACT_SALES.UNIT_PRICE IS '成交單價（未扣折扣）'
/
COMMENT ON COLUMN FACT_SALES.DISCOUNT_AMOUNT IS '整行折扣金額'
/
COMMENT ON COLUMN FACT_SALES.COST_AMOUNT IS '銷貨成本 = QUANTITY * 當日單位成本'
